Repository Gaming-Linux-FR/GLF-OS, pull requests merged in 2025-01, with the labels that each got.

#103 Ajout de templates pour les issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: enhancement

#139 Correctif de la commande dans le template des issues
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: enhancement

#100 Passage au flocon
  .github/workflows/nix-build.yml
  .gitignore
  Makefile
  assets/wallpaper/dark.jpg
  assets/wallpaper/white.jpg
  flake.nix
  iso-cfg/configuration.nix
  iso-cfg/customConfig/default.nix
  iso-cfg/flake.lock
  iso-cfg/flake.nix
  modules/default/aliases.nix
  modules/default/boot.nix
  modules/default/debug.nix
  modules/default/default.nix
  modules/default/firefox.nix
  modules/default/fstrim.nix
  modules/default/gaming.nix
  modules/default/gnome.nix
  modules/default/nh.nix
  modules/default/nvidia.nix
  modules/default/packages.nix
  modules/default/pipewire.nix
  modules/default/printing.nix
  modules/default/system.nix
  modules/default/update.nix
  modules/default/version.nix
  nix-cfg/glf/boot.nix
  nix-cfg/glf/default.nix
  nix-cfg/glf/firefox.nix
  nix-cfg/glf/fstrim.nix
  nix-cfg/glf/gaming.nix
  nix-cfg/glf/gnome.nix
  nix-cfg/glf/imprimante.nix
  nix-cfg/glf/nh.nix
  nix-cfg/glf/paquets.nix
  nix-cfg/glf/pipewire.nix
  nix-cfg/glf/system.nix
  nix-cfg/glf/updateConf.nix
  nix-cfg/hardware-configuration.nix
  patches/calamares-nixos-extensions/modules/nixos/main.py
Labels: enhancement

#147 improve flake, workflow for test user configurations
  .github/workflows/nix-build.yml
  flake.nix
Labels: enhancement

#109 #108 Fixes impression et scan
  .gitignore
  modules/default/printing.nix
  patches/calamares-nixos-extensions/modules/nixos/main.py
Labels: enhancement

#153 Les liens externe s'ouvrent dans un nouvel onglet
  .gitignore
  docs/.bundle/config
  docs/_config.yml
  flake.nix
Labels: documentation

#128 Enable AppImage
  modules/default/packages.nix
Labels: enhancement

#119 Add Swap
  modules/default/system.nix
Labels: enhancement

#118 Improve GPU
  modules/default/system.nix
Labels: enhancement

#156 fix nvidia standby
  modules/default/default.nix
  modules/default/nvidia.nix
  modules/default/standBy.nix
Labels: bug

#163 fix actionDocs
  .github/workflows/pages.yaml
Labels: bug, documentation

#162 fix path docs
  docs/pages/documentation/Installation.md
  docs/pages/documentation/installPackageFromNix.md
Labels: bug, documentation

#165 Mise à jours des flocons
  .github/workflows/nix-build.yml
  flake.lock
  iso-cfg/flake.lock
  modules/default/gnome.nix
Labels: FlakeUpdate

#166 Merge dev -> main
  .github/workflows/nix-build.yml
  flake.lock
  iso-cfg/flake.lock
  modules/default/gnome.nix
  modules/default/packages.nix
Labels: enhancement, FlakeUpdate

#167 update all flakes
  iso-cfg/flake.lock
Labels: FlakeUpdate

#170 switch from systemd-boot to grub for efi
  patches/calamares-nixos-extensions/modules/nixos/main.py
Labels: enhancement

#171 update flake
  flake.lock
  iso-cfg/flake.lock
Labels: FlakeUpdate
